dist: trusty
sudo: false

language: node_js
node_js:
  - 8
cache: yarn

script:
  - yarn eslint
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $CI_USER_TOKEN
  local_dir: dist
